blog/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

extra_patterns = [
     url(r'^$', views.Music.as_view(), name="Music"),
     url(r'^popular/(?P<kw>[\w]+)?/?$', views.PopularMusic.as_view(), name="PopularMusic"),
     url(r'^genre/(?P<kw>[\w]+)?/?$', views.MusicByGenre.as_view(), name="MusicByGenre"),
     url(r'^trending/$', views.TrendingMusic.as_view(),  name="TrendingMusic"),
     url(r'^random/$', views.random_song, name="random_song"),
 ]

urlpatterns = [
    url(r'^$', views.index.as_view(), name='index'),
    url(r'^musicblog/', include(extra_patterns)),
    url(r'^(?P<slug>[\w\-]+)blog/$', views.feed.as_view(), name="feed"),
    url(r'^(?P<slug>[\w\-]+)blog/(?P<pk>[0-9]+)/$', views.BlogPost.as_view(), name="BlogPost"),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.profile_page.as_view(), name="profile_page"),
    url(r'^playlist/$', views.Playlist_Feed.as_view(), name="playlist_feed"),
    url(r'^playlist/(?P<pk>[0-9]+)', views.Playlist_View.as_view(), name="playlist"),
    url(r'^about/$', views.about, name="about"),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': reverse_lazy('blog:login')}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^search/$', views.Search_Results.as_view(), name="search"),
    url(r'^add_feed/$', views.add_feed, name="add_feed"),
    url(r'^view_incrementor/$', views.view_incrementor, name="view_incrementor"),
    url(r'^post/add_like/$', views.add_like, name="add_like"),
    url(r'^fetch_music/(?P<kw>[\w]+)/$', views.music_by_genre.as_view(), name="music_by_genre"),
    url(r'^fetch_user_playlists/(?P<pk>[0-9]+)/$', views.fetch_user_playlists, name="user_playlists"),
    url(r'^post_comment/(?P<post_id>[0-9]+)/$', views.post_comment, name="post_comment"),
    url(r'^popular_music/(?P<kw>[\w]+)/$', views.popular_music.as_view(), name="popular_music"),
    url(r'^add_post/$', views.add_post.as_view(), name='add_post'),
    url(r'^add_song/$', views.add_song.as_view(), name='add_song'),
    url(r'^add_to_playlist/$', views.add_to_playlist, name="add_to_playlist"),
    url(r'^create_playlist/(?P<song_id>[0-9]+)/$', views.create_playlist, name="create_playlist"),
    url(r'^edit_playlist/$', views.edit_playlist, name="edit_playlist"),
    url(r'^delete_post/$', views.delete_post, name="delete_post"),
    url(r'^add_suggestion/$', views.suggestions, name="suggestions"),
    url(r'^submit_music/$', views.submit_music, name="submit_music"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('blog.urls')),
    url('', include('social.apps.django_app.urls',namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from ordered_model.models import OrderedModel
from django.utils.text import slugify
from django.contrib.auth.models import AbstractUser
from embed_video.fields import EmbedVideoField
from django.core.files import File
from django.conf import settings
import datetime
import urllib.parse
import os

class Feed(models.Model):
    title = models.CharField(max_length=40)
    description = models.CharField(max_length=200)
    url = models.URLField(blank=True)
    slug = models.SlugField(max_length=40, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return '{}blog/'.format(self.slug)

    def save(self):
        if not self.slug:
            self.slug = slugify(self.title)
            self.url = "blog/{}".format(self.slug)
        super(Feed, self).save()

class UserProfile(AbstractUser):
    signup_date = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(
            'Post',
            through='Like',
            through_fields=('user', 'post'),
            blank=True,
            related_name='liked_by',
    )

    def __str__(self):
        return self.username

class Post(models.Model):
    feed = models.ForeignKey(Feed, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    comments = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='Comment',
        through_fields=('post', 'userprofile'),
        related_name='commenter',
        blank=True,
    )
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="post_images/", blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    num_likes = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    is_song = models.BooleanField(default=False)
    is_playlist = models.BooleanField(default=False)
    is_private = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def increment_view_count(self):
        self.views = self.views + 1
        self.save()
        return self.views

    def increment_like_count(self):
        likes = self.num_likes + 1
        self.num_likes = likes
        self.save()

    def get_absolute_url(self):
        if self.is_playlist:
            return 'http://www.millennialsmusic.com/playlist/{}'.format(self.id)
        else:
            return 'http://www.millennialsmusic.com/{}blog/{}'.format(self.feed.slug, self.id)


    def quote_url(self):
        return urllib.parse.quote(self.get_absolute_url())


class Song(models.Model):
    artist = models.CharField(max_length=50)
    song_name = models.CharField(max_length=100, unique=True)
    feat_artist = models.CharField(max_length=50, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    video = EmbedVideoField(unique=True)
    video_id = models.CharField(max_length=20, blank=True)
    post = models.OneToOneField(Post, on_delete=models.CASCADE, blank=True)
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    lyrics = models.TextField(blank=True)
    image = models.ImageField(upload_to="song_images/", blank=True)

    class Meta:
        unique_together = ('artist', 'song_name',)

    def _get_full_name(self):
        if self.feat_artist:
            return '{} - {} (Ft. {})'.format(self.artist, self.song_name, self.feat_artist)

        return '{} - {}'.format(self.artist, self.song_name)

    def set_lyrics(self, song, artist):
        self.lyrics = fetch_lyrics(song, artist)
        return self.lyrics

    def grep_video_id(self):
        if not self.video_id:
            import re
            idRegex = re.compile(r'(?<=\?v=).{11}')
            self.video_id = idRegex.search(self.video).group()
        return self.video_id

    def set_image(self, video_id):
        f, fn = retrieve_thumbnail(video_id)
        self.image.save(fn, f, save=False)

    full_name = property(_get_full_name)

    def __str__(self):
        return self.full_name

    def save(self, *args, **kwargs):
        if not self.pk:
            self.set_lyrics(self.song_name, self.artist)
            self.set_image(self.grep_video_id())
            self.post = Post.objects.create(feed=Feed.objects.get(title='Music'),
                                    title=self.full_name, author=self.added_by,
                                    description=self.lyrics,
                                    image=self.image,
                                    is_song=True)
        super(Song, self).save(*args, **kwargs)
        self.post.tags = self.tags.all()
        self.post.save()


class Playlist(models.Model):
    name = models.CharField(max_length=100)
    pub_date = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    song_list = models.TextField(blank=True)
    songs = models.ManyToManyField('Song', through='PlaylistEntry')
    image = models.ImageField(upload_to="playlist_images/", blank=True)
    tags = models.ManyToManyField('Tag')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.OneToOneField(Post, on_delete=models.CASCADE, blank=True)
    is_private = models.BooleanField(default=False)

    class Meta:
        unique_together = ('name', 'created_by',)

    def create_song_list(self):
        names = ""
        i = 1
        for song in self.songs.all():
            formatted_name = str(i) + ") " + song.full_name + "\n"
            names += formatted_name
            i += 1
        return names

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.pk:
            self.post = Post.objects.create(feed=Feed.objects.get(title='Playlists'),
                        title=self.name, author=self.created_by,
                        description=self.description, image=self.image,
                        is_playlist=True,
                        is_private=self.is_private)

        super(Playlist, self).save(*args, **kwargs)
        self.post.tags = Tag.objects.filter(name='PLLST')
        self.post.save()

class PlaylistEntry(OrderedModel):
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    order_with_respect_to = 'playlist'

    class Meta(OrderedModel.Meta):
        ordering = ('playlist','order')


class Comment(models.Model):
    body = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    userprofile = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True)
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)

    def __str__(self):
        return "{}-{}: {}".format(self.userprofile, self.post, self.pub_date)

    def upvote_comment(self):
        count = self.upvotes + 1
        self.upvotes = count

    def upvote_comment(self):
        count = self.downvotes + 1
        self.downvotes = count

class Like(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__ (self):
        return "{} liked by: {}".format(str(self.post), str(self.user))

    def save(self, **kwargs):
        self.post.increment_like_count()
        super(Like, self).save(**kwargs)

class Tag(models.Model):
    TAG_CHOICES = (
        ('ACSTC','Acoustic'),
        ('ALTR', 'Alt Rock'),
        ('ALT', 'Alternative'),
        ('CLSR', 'Classic Rock'),
        ('ELEC', 'Electronic'),
        ('FEML', 'Female Vocals'),
        ('FLK', 'Folk'),
        ('FNK', 'Funk'),
        ('HH', 'Hip-Hop'),
        ('IND', 'Indie'),
        ('POP', 'Pop.'),
        ('PSYCH', 'Psychedelic'),
        ('PUNK', 'Punk Rock'),
        ('RB', "R & B"),
        ('REG', 'Reggae'),
        ('RMX', 'Remix'),
        ('SOUL', 'Soul'),
        ('SKA', 'Ska'),
        ('PLLST', 'Playlist'),
    )
    name = models.CharField(max_length=5, choices=TAG_CHOICES)
    def __str__(self):
        return self.name


class Suggestion(models.Model):
    what = models.CharField(max_length=144)
    how = models.TextField(max_length=250,blank=True)
    def __str__(self):
        return self.what

class MusicRecommendation(models.Model):
    artist = models.CharField(max_length=100)
    song_name = models.CharField(max_length=100)
    user = models.ForeignKey(UserProfile, blank=True)
    url = models.URLField(blank=True)
    def __str__(self):
        return "{} - {}".format(self.artist, self.song_name)

def retrieve_thumbnail(vid_id):
    import urllib.request
    from django.core.files import File

    def create_url(v_id):
        base_url = 'http://img.youtube.com/vi/'
        url = base_url + v_id +'/0.jpg'
        return url

    def fetch_jpg(url, v_id):
        sauce = urllib.request.urlopen(url).read()
        fn = str(v_id) + '.jpg'
        path = settings.MEDIA_ROOT + '/post_images/' + fn
        with open(path, 'wb') as f:
            myfile = File(f)
            myfile.write(sauce)
            f.close()
        return (path, fn)

    URL = create_url(vid_id)
    path, fn = fetch_jpg(URL, vid_id)
    reopen_f = open(path, 'rb')
    django_file = File(reopen_f)
    return (django_file, fn)

def fetch_lyrics(song_title, artist_name):
    import requests
    from bs4 import BeautifulSoup
    from secrets import GENIUS_AUTH_TOKEN

    headers = {'Authorization': GENIUS_AUTH_TOKEN}

    base_url = "http://api.genius.com"
    search_url = base_url + "/search"

    def lyrics_from_song_api_path(song_api_path):

blog/forms.py
from django import forms
from django.forms import ModelForm
from .models import Feed, Post, UserProfile, Comment, Song, Playlist, Suggestion, MusicRecommendation
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field, HTML
from crispy_forms.bootstrap import FormActions, StrictButton

class FeedForm(ModelForm):
    class Meta:
        model = Feed
        fields = ['title', 'description']
        labels = {
        'title': "Title:",
        'description': "Description:",
        }

class PostForm(ModelForm):
    description = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Post
        fields = ['feed', 'title', 'description', 'image', 'tags']
        labels = {
        'feed': "Feed:",
        'title': "Title:",
        'description': "Description:",
        'image': "Image:",
        'tags': 'Tags:',
        }

class SongForm(ModelForm):

    class Meta:
        model = Song
        fields = ['artist', 'song_name', 'video', 'tags']


class UserProfileForm(ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}
    ), label="Password")
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}
    ), label="Confirm Password")

    class Meta:
        model = UserProfile
        fields = ['username', 'email']
        widgets = {
            'username': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Enter Username'}
            ),
            'email': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Enter Email'}
            ),
            'password1': forms.PasswordInput(
                attrs={'class': 'form-control', 'placeholder': 'Password'}
            ),
            'password1': forms.PasswordInput(
                attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}
            ),
        }

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super(UserProfileForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class PlaylistForm(ModelForm):

    class Meta:
        model = Playlist
        fields = ['name', 'description', 'image', 'is_private']
        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': "playlist name..."}
            ),
            'description': forms.Textarea(
                attrs={'class':'form-control', "rows":'4', 'placeholder':"my favorite [insert genre] songs..."}
            ),
            'image': forms.FileInput(
                attrs={'id':"playlistImage"}
            ),
        }

        labels = {
        'name': 'Playlist Name',
        'description': 'Description',
        'image': "Playlist Image",
        'is_private': "I want this playlist to be private"
        }


class CommentForm(ModelForm):
    body = forms.CharField(widget=forms.Textarea(
        attrs={'class':'form-control', 'placeholder':"comment...", "rows":'6'}
    ))
    class Meta:
        model = Comment
        fields = ['body',]

class SubmitMusicForm(ModelForm):
    artist = forms.CharField(required=True, label="Artist", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "artist's name..."}
        ));
    song_name = forms.CharField(required=True, label="Song Name", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "song's name..."}
    ));
    url = forms.CharField(required=False, label="Video Url", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "optional url to music video..."}
    ));
    class Meta:
        model = MusicRecommendation
        fields = ['artist', 'song_name', 'url']


class SuggestionsForm(ModelForm):
    what = forms.CharField(required=True, label="What Needs Improvement?", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "what about this website pisses you off..."}
    ));
    how = forms.CharField(label="How Should I Improve it?", widget=forms.Textarea(
        attrs={'class':'form-control', 'placeholder':"suggestions or example of website that does it better...", "rows":'4'}
    ));
    class Meta:
        model = Suggestion
        fields = ['what', 'how']

blog/templates/snippets/music_post_cell.html
{% load staticfiles %}

<div class="row">
<div class="col-sm-12">
  <div class="panel panel-default post-container">
    <div>
      <div class="panel-header text-center">
        <a href="{% url 'blog:BlogPost' slug=post.feed.slug pk=post.id %}" style="color:#212121;"><h4>{{ post.title }}</h4></a>
      </div>
    </div>
    <div class="youtube-player" data-id="{{ post.song.video_id }}">
    <div class="row">
      <div class="col-sm-3">
      <div class="panel-body">

        {% if post.image %}
          <div id="img-container" style="width:200px;height:150px">
            <img src="/media/{{ post.image }}" class="img-rounded img-responsive center-block"></img>
          </div>
        {% else %}
          <div id="img-container" style="width:200px;height:150px">
            <img src="/media/{{ post.image }}" class="img-rounded img-responsive center-block"></img>
          </div>
        {% endif %}
          <button class="button img-circle mv-btn" data-id="{{ post.song.video_id }}" data-view-url="{% url 'blog:view_incrementor' %}">
            {% csrf_token %}
            <i class="fa fa-play-circle-o fa-5x"></i>
          </button>

      </div>
      </div>
      <div class="col-sm-4 col-sm-offset-1">

      <div class="panel-body text-center">{{ post.description|truncatewords_html:20|linebreaks }}</div>
      <div class="text-center col-sm-12 hidden text-scroller" id="lyric-scroller"
        style="height:180px;overflow:auto;">{{ post.description|linebreaks }}
      </div>
      <div class="row">
      <div class="col-sm-12">
        <div class="wrapper text-center">
        <button class="btn btn-default lyrics-button borderless"><i class="fa fa-ellipsis-h fa-2x"></i></button>
        </div>
      </div>
      </div>

      </div>
      <div class="col-sm-3 col-sm-offset-1">
        <div class="btn-group-vertical pull-right">
          {% include 'buttons/cell_like_button.html' %}

            <button class="btn btn-default yt-button">
              <a href="{{post.song.video}}" target="_blank">
              <i class="fa fa-youtube fa-2x"></i>
              </a>
            </button>

            {% include 'buttons/fb_share_button.html' %}

            {% include 'buttons/twitter_share_button.html' %}
        </div>
    </div>
  </div>
</div>
  <div class="panel-footer" style="background-color:#ffffff;">
  <div class="row">
  <div class="col-sm-3">
    <span class="views text-left"><strong class="view-count">Views: {{ post.views }}</strong></span>
  </div>
    <div class="wrapper text-center col-sm-6">
    <strong>Music Genre(s): </strong>
      <div class="btn-group">
        {% for tag in post.song.tags.all %}
        <a href="{% url 'blog:MusicByGenre' kw=tag.name %}"><button class="btn btn-default genre-button">{{tag.get_name_display}}</button></a>
        {% endfor %}
      </div>
    </div>
    <span >
    {% include 'buttons/cell_playlist_button.html' %}

  </div>
  </div>
  </div>
</div>
</div>

blog/templates/snippets/navbar.html
<nav class="navbar navbar-inverse no-margin navbar-fixed-top" style="background-color:#000;">
  <div class="container-fluid">
    <div class="">
      <ul class="nav navbar-nav navbar-left navbar-head">
        <li>
          <button class="btn btn-primary btn-sm navbar-btn" id="menu-toggle-2" style="margin-left:-5px;">
            <i class="fa fa-bars fa-lg"></i>
          </button>
        </li>
        <li>
          <a class="navbar-brand" href="/" style="margin-left:0px">Millennials Music</a>
        </li>
        <li>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false" aria-controls="navbar-collapse">
            <i class="fa fa-bars fa-lg"></i>
          </button>
        </li>
      </ul>


    </div>

    <div class="navbar-collapse collapse" id="navbar-collapse">

       <ul class="nav navbar-nav navbar-right">
         <li>
         <form class="navbar-form" method="get" action="{% url 'blog:search' %}" style="display:none;">
           <div class="form-group">
             <input type="text" name="q" class="form-control" placeholder="Search...">
             <button class="btn btn-default" type="submit">Submit</button>
           </div>
         </form>
       </li>
       <li>
         <button class="btn btn-default navbar-btn btn-sm search-button">
           <i class = "fa fa-search fa-lg"></i>
         </button>
       </li>
         {% if user.is_authenticated %}
         <li><a href="/logout">Logout</a></li>
         {% else %}

         <li><a href="{% url 'blog:login' %}">sign in</a></li>
         <li><a href="{% url 'blog:register' %}">sign up</a></li>

         {% endif %}

      </ul>

    </div>
  </div>
</nav>

blog/templates/snippets/post_cells.html
{% if post.is_song %}
  {% include 'snippets/music_post_cell.html' %}
{% else %}
  {% include 'snippets/textbased_post_cell.html' %}
{% endif %}

blog/templates/snippets/sidebar.html
<div id="sidebar-wrapper">
      <ul class="sidebar-nav nav-pills nav-stacked" id="menu">

          {% if user.is_authenticated %}
          <li>
            <a href="/profile/{{ user.pk }}">
              <span class="fa-stack fa-lg pull-left">
                <i class="fa fa-user-circle-o fa-stack-1x"></i>
              </span>My Profile</a>
          </li>
          {% endif %}

          <li>
             <a href="{% url 'blog:Music' %}"><span class="fa-stack fa-lg pull-left"><i class="fa fa-music fa-stack-1x "></i></span>Music</a>
                <ul class="nav-pills nav-stacked" style="list-style-type:none;">
                 <li><a href="{% url 'blog:PopularMusic' %}">Popular</a></li>
                 <li><a href="{% url 'blog:MusicByGenre' %}">By Genre</a></li>
                 <li><a href="{% url 'blog:random_song' %}">Random Song</a></li>
             </ul>
         </li>
         <li>
             <a href="{% url "blog:playlist_feed" %}"> <span class="fa-stack fa-lg pull-left"><i class="fa fa-youtube-play fa-stack-1x "></i></span>Playlists</a>
         </li>
         <li>
           <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-users fa-stack-1x "></i></span>Community</a>
           <ul class="nav-pills nav-stacked" style="list-style-type:none;">
               <li><a href="{% url "blog:suggestions" %}"><span class="fa-stack fa-lg pull-left"><i class="fa fa-envelope fa-stack-1x "></i></span>Suggestions</a></li>
               <li><a href="{% url "blog:submit_music" %}"><span class="fa-stack fa-lg pull-left"><i class="fa fa-gift fa-stack-1x "></i></span>Submit Music</a></li>
           </ul>
         </li>
         <li>
             <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-newspaper-o fa-stack-1x "></i></span>Articles</a>
             <ul class="nav-pills nav-stacked" style="list-style-type:none;">
                 <li><a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-flag fa-stack-1x "></i></span>News</a></li>
                 <li><a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-flag fa-stack-1x "></i></span>Pop. Culture</a></li>
                 <li><a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-flag fa-stack-1x "></i></span>Music Reviews</a></li>

             </ul>
         </li>

         <li>
             <a href="{% url 'blog:about' %}"><span class="fa-stack fa-lg pull-left"><i class="fa fa-info-circle fa-stack-1x "></i></span>About</a>
         </li>
         <div class="row">
           <div class="col-sm-12">
           <br/>
           <span class="text-center" style="color:#999999;;"><h4 style="opacity:0.7;">Connect</h4></span>
           <br/>
           <div class="wrapper text-center">
           <div class="row">
               <a href="https://twitter.com/MillennialMuzik" class="twitter-follow-button"
                data-size="large" data-show-screen-name="false" data-show-count="false">
                Follow @MillennialMuzik
              </a>
          </div>
          <div class="row">
             <div class="fb-follow" data-href="https://www.facebook.com/MillennialMuzik"
              data-layout="button" data-size="large" data-show-faces="false">
            </div>
          </div>
        </div>
      </div>
      </div>
      </ul>

</div>

blog/templates/snippets/textbased_post_cell.html
{% load staticfiles %}


<div class="row">
<div class="col-sm-12">
  <div class="panel panel-default post-container">
    <div>
      <div class="panel-header text-center">
        {% if post.is_playlist %}
        <a href="{% url 'blog:playlist' pk=post.id %}" style="color:#212121;"><h4>{{ post.title }}</h4></a>
        {% else %}
        <a href="{% url 'blog:BlogPost' slug=post.feed.slug pk=post.id %}" style="color:#212121;"><h4>{{ post.title }}</h4></a>
        {% endif %}
      </div>
    </div>
    <div class="row">
      <div class="col-sm-3">
      <div class="panel-body">

        {% if post.image %}
          <img src="/media/{{ post.image }}" class="img-rounded" id="img-container" style="width:200px;height:150px" />
        {% else %}
          <img src="{% static "blog/public/images/millennialsmusic_icon.jpg" %}" class="img-rounded" style="width:150px;height:150px" />
        {% endif %}


      </div>
      </div>
      <div class="col-sm-6">

      <div class="panel-body text-center">{{ post.description|truncatewords_html:40|linebreaks }}</div>
      </div>
      <div class="col-sm-3">
        <div class="btn-group-vertical pull-right">
            {% include 'buttons/cell_like_button.html' %}
            {% include 'buttons/fb_share_button.html' %}
            {% include 'buttons/twitter_share_button.html' %}
        </div>
    </div>
    </div>
    <div class="panel-footer" style="background-color:#ffffff;">
      <span class="views text-right">
        {% if post.is_playlist %}
        <strong>created by: {{ post.author }}</strong> | <strong> {{post.pub_date|timesince}}</strong></span>
        {% else %}
        <strong>written by: {{ post.author }}</strong> | <strong> {{post.pub_date|timesince}}</strong></span>
        {% endif %}
    </div>
  </div>
  </div>
</div>