blog/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

extra_patterns = [
     url(r'^$', views.Music.as_view(), name="Music"),
     url(r'^popular/(?P<kw>[\w]+)?/?$', views.PopularMusic.as_view(), name="PopularMusic"),
     url(r'^genre/(?P<kw>[\w]+)?/?$', views.MusicByGenre.as_view(), name="MusicByGenre"),
     url(r'^trending/$', views.TrendingMusic.as_view(),  name="TrendingMusic"),
     url(r'^random/$', views.random_song, name="random_song"),
 ]

urlpatterns = [
    url(r'^$', views.index.as_view(), name='index'),
    url(r'^musicblog/', include(extra_patterns)),
    url(r'^(?P<slug>[\w\-]+)blog/$', views.feed.as_view(), name="feed"),
    url(r'^(?P<slug>[\w\-]+)blog/(?P<pk>[0-9]+)/$', views.BlogPost.as_view(), name="BlogPost"),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.profile_page.as_view(), name="profile_page"),
    url(r'^playlist/$', views.Playlist_Feed.as_view(), name="playlist_feed"),
    url(r'^playlist/(?P<pk>[0-9]+)', views.Playlist_View.as_view(), name="playlist"),
    url(r'^about/$', views.about, name="about"),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': reverse_lazy('blog:login')}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^search/$', views.Search_Results.as_view(), name="search"),
    url(r'^add_feed/$', views.add_feed, name="add_feed"),
    url(r'^view_incrementor/$', views.view_incrementor, name="view_incrementor"),
    url(r'^post/add_like/$', views.add_like, name="add_like"),
    url(r'^fetch_music/(?P<kw>[\w]+)/$', views.music_by_genre.as_view(), name="music_by_genre"),
    url(r'^fetch_user_playlists/(?P<pk>[0-9]+)/$', views.fetch_user_playlists, name="user_playlists"),
    url(r'^post_comment/(?P<post_id>[0-9]+)/$', views.post_comment, name="post_comment"),
    url(r'^popular_music/(?P<kw>[\w]+)/$', views.popular_music.as_view(), name="popular_music"),
    url(r'^add_post/$', views.add_post.as_view(), name='add_post'),
    url(r'^add_song/$', views.add_song.as_view(), name='add_song'),
    url(r'^add_to_playlist/$', views.add_to_playlist, name="add_to_playlist"),
    url(r'^create_playlist/(?P<song_id>[0-9]+)/$', views.create_playlist, name="create_playlist"),
    url(r'^edit_playlist/$', views.edit_playlist, name="edit_playlist"),
    url(r'^delete_post/$', views.delete_post, name="delete_post"),
    url(r'^add_suggestion/$', views.suggestions, name="suggestions"),
    url(r'^submit_music/$', views.submit_music, name="submit_music"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('blog.urls')),
    url('', include('social.apps.django_app.urls',namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from ordered_model.models import OrderedModel
from django.utils.text import slugify
from django.contrib.auth.models import AbstractUser
from embed_video.fields import EmbedVideoField
from django.core.files import File
from django.conf import settings
import datetime
import urllib.parse
import os

class Feed(models.Model):
    title = models.CharField(max_length=40)
    description = models.CharField(max_length=200)
    url = models.URLField(blank=True)
    slug = models.SlugField(max_length=40, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return '{}blog/'.format(self.slug)

    def save(self):
        if not self.slug:
            self.slug = slugify(self.title)
            self.url = "blog/{}".format(self.slug)
        super(Feed, self).save()

class UserProfile(AbstractUser):
    signup_date = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(
            'Post',
            through='Like',
            through_fields=('user', 'post'),
            blank=True,
            related_name='liked_by',
    )

    def __str__(self):
        return self.username

class Post(models.Model):
    feed = models.ForeignKey(Feed, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    comments = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='Comment',
        through_fields=('post', 'userprofile'),
        related_name='commenter',
        blank=True,
    )
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="post_images/", blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    num_likes = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    is_song = models.BooleanField(default=False)
    is_playlist = models.BooleanField(default=False)
    is_private = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def increment_view_count(self):
        self.views = self.views + 1
        self.save()
        return self.views

    def increment_like_count(self):
        likes = self.num_likes + 1
        self.num_likes = likes
        self.save()

    def get_absolute_url(self):
        if self.is_playlist:
            return 'http://www.millennialsmusic.com/playlist/{}'.format(self.id)
        else:
            return 'http://www.millennialsmusic.com/{}blog/{}'.format(self.feed.slug, self.id)


    def quote_url(self):
        return urllib.parse.quote(self.get_absolute_url())


class Song(models.Model):
    artist = models.CharField(max_length=50)
    song_name = models.CharField(max_length=100, unique=True)
    feat_artist = models.CharField(max_length=50, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    video = EmbedVideoField(unique=True)
    video_id = models.CharField(max_length=20, blank=True)
    post = models.OneToOneField(Post, on_delete=models.CASCADE, blank=True)
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    lyrics = models.TextField(blank=True)
    image = models.ImageField(upload_to="song_images/", blank=True)

    class Meta:
        unique_together = ('artist', 'song_name',)

    def _get_full_name(self):
        if self.feat_artist:
            return '{} - {} (Ft. {})'.format(self.artist, self.song_name, self.feat_artist)

        return '{} - {}'.format(self.artist, self.song_name)

    def set_lyrics(self, song, artist):
        self.lyrics = fetch_lyrics(song, artist)
        return self.lyrics

    def grep_video_id(self):
        if not self.video_id:
            import re
            idRegex = re.compile(r'(?<=\?v=).{11}')
            self.video_id = idRegex.search(self.video).group()
        return self.video_id

    def set_image(self, video_id):
        f, fn = retrieve_thumbnail(video_id)
        self.image.save(fn, f, save=False)

    full_name = property(_get_full_name)

    def __str__(self):
        return self.full_name

    def save(self, *args, **kwargs):
        if not self.pk:
            self.set_lyrics(self.song_name, self.artist)
            self.set_image(self.grep_video_id())
            self.post = Post.objects.create(feed=Feed.objects.get(title='Music'),
                                    title=self.full_name, author=self.added_by,
                                    description=self.lyrics,
                                    image=self.image,
                                    is_song=True)
        super(Song, self).save(*args, **kwargs)
        self.post.tags = self.tags.all()
        self.post.save()


class Playlist(models.Model):
    name = models.CharField(max_length=100)
    pub_date = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    song_list = models.TextField(blank=True)
    songs = models.ManyToManyField('Song', through='PlaylistEntry')
    image = models.ImageField(upload_to="playlist_images/", blank=True)
    tags = models.ManyToManyField('Tag')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.OneToOneField(Post, on_delete=models.CASCADE, blank=True)
    is_private = models.BooleanField(default=False)

    class Meta:
        unique_together = ('name', 'created_by',)

    def create_song_list(self):
        names = ""
        i = 1
        for song in self.songs.all():
            formatted_name = str(i) + ") " + song.full_name + "\n"
            names += formatted_name
            i += 1
        return names

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.pk:
            self.post = Post.objects.create(feed=Feed.objects.get(title='Playlists'),
                        title=self.name, author=self.created_by,
                        description=self.description, image=self.image,
                        is_playlist=True,
                        is_private=self.is_private)

        super(Playlist, self).save(*args, **kwargs)
        self.post.tags = Tag.objects.filter(name='PLLST')
        self.post.save()

class PlaylistEntry(OrderedModel):
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    order_with_respect_to = 'playlist'

    class Meta(OrderedModel.Meta):
        ordering = ('playlist','order')


class Comment(models.Model):
    body = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    userprofile = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True)
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)

    def __str__(self):
        return "{}-{}: {}".format(self.userprofile, self.post, self.pub_date)

    def upvote_comment(self):
        count = self.upvotes + 1
        self.upvotes = count

    def upvote_comment(self):
        count = self.downvotes + 1
        self.downvotes = count

class Like(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__ (self):
        return "{} liked by: {}".format(str(self.post), str(self.user))

    def save(self, **kwargs):
        self.post.increment_like_count()
        super(Like, self).save(**kwargs)

class Tag(models.Model):
    TAG_CHOICES = (
        ('ACSTC','Acoustic'),
        ('ALTR', 'Alt Rock'),
        ('ALT', 'Alternative'),
        ('CLSR', 'Classic Rock'),
        ('ELEC', 'Electronic'),
        ('FEML', 'Female Vocals'),
        ('FLK', 'Folk'),
        ('FNK', 'Funk'),
        ('HH', 'Hip-Hop'),
        ('IND', 'Indie'),
        ('POP', 'Pop.'),
        ('PSYCH', 'Psychedelic'),
        ('PUNK', 'Punk Rock'),
        ('RB', "R & B"),
        ('REG', 'Reggae'),
        ('RMX', 'Remix'),
        ('SOUL', 'Soul'),
        ('SKA', 'Ska'),
        ('PLLST', 'Playlist'),
    )
    name = models.CharField(max_length=5, choices=TAG_CHOICES)
    def __str__(self):
        return self.name


class Suggestion(models.Model):
    what = models.CharField(max_length=144)
    how = models.TextField(max_length=250,blank=True)
    def __str__(self):
        return self.what

class MusicRecommendation(models.Model):
    artist = models.CharField(max_length=100)
    song_name = models.CharField(max_length=100)
    user = models.ForeignKey(UserProfile, blank=True)
    url = models.URLField(blank=True)
    def __str__(self):
        return "{} - {}".format(self.artist, self.song_name)

def retrieve_thumbnail(vid_id):
    import urllib.request
    from django.core.files import File

    def create_url(v_id):
        base_url = 'http://img.youtube.com/vi/'
        url = base_url + v_id +'/0.jpg'
        return url

    def fetch_jpg(url, v_id):
        sauce = urllib.request.urlopen(url).read()
        fn = str(v_id) + '.jpg'
        path = settings.MEDIA_ROOT + '/post_images/' + fn
        with open(path, 'wb') as f:
            myfile = File(f)
            myfile.write(sauce)
            f.close()
        return (path, fn)

    URL = create_url(vid_id)
    path, fn = fetch_jpg(URL, vid_id)
    reopen_f = open(path, 'rb')
    django_file = File(reopen_f)
    return (django_file, fn)

def fetch_lyrics(song_title, artist_name):
    import requests
    from bs4 import BeautifulSoup
    from secrets import GENIUS_AUTH_TOKEN

    headers = {'Authorization': GENIUS_AUTH_TOKEN}

    base_url = "http://api.genius.com"
    search_url = base_url + "/search"

    def lyrics_from_song_api_path(song_api_path):

blog/forms.py
from django import forms
from django.forms import ModelForm
from .models import Feed, Post, UserProfile, Comment, Song, Playlist, Suggestion, MusicRecommendation
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field, HTML
from crispy_forms.bootstrap import FormActions, StrictButton

class FeedForm(ModelForm):
    class Meta:
        model = Feed
        fields = ['title', 'description']
        labels = {
        'title': "Title:",
        'description': "Description:",
        }

class PostForm(ModelForm):
    description = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Post
        fields = ['feed', 'title', 'description', 'image', 'tags']
        labels = {
        'feed': "Feed:",
        'title': "Title:",
        'description': "Description:",
        'image': "Image:",
        'tags': 'Tags:',
        }

class SongForm(ModelForm):

    class Meta:
        model = Song
        fields = ['artist', 'song_name', 'video', 'tags']


class UserProfileForm(ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}
    ), label="Password")
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}
    ), label="Confirm Password")

    class Meta:
        model = UserProfile
        fields = ['username', 'email']
        widgets = {
            'username': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Enter Username'}
            ),
            'email': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Enter Email'}
            ),
            'password1': forms.PasswordInput(
                attrs={'class': 'form-control', 'placeholder': 'Password'}
            ),
            'password1': forms.PasswordInput(
                attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}
            ),
        }

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super(UserProfileForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class PlaylistForm(ModelForm):

    class Meta:
        model = Playlist
        fields = ['name', 'description', 'image', 'is_private']
        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': "playlist name..."}
            ),
            'description': forms.Textarea(
                attrs={'class':'form-control', "rows":'4', 'placeholder':"my favorite [insert genre] songs..."}
            ),
            'image': forms.FileInput(
                attrs={'id':"playlistImage"}
            ),
        }

        labels = {
        'name': 'Playlist Name',
        'description': 'Description',
        'image': "Playlist Image",
        'is_private': "I want this playlist to be private"
        }


class CommentForm(ModelForm):
    body = forms.CharField(widget=forms.Textarea(
        attrs={'class':'form-control', 'placeholder':"comment...", "rows":'6'}
    ))
    class Meta:
        model = Comment
        fields = ['body',]

class SubmitMusicForm(ModelForm):
    artist = forms.CharField(required=True, label="Artist", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "artist's name..."}
        ));
    song_name = forms.CharField(required=True, label="Song Name", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "song's name..."}
    ));
    url = forms.CharField(required=False, label="Video Url", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "optional url to music video..."}
    ));
    class Meta:
        model = MusicRecommendation
        fields = ['artist', 'song_name', 'url']


class SuggestionsForm(ModelForm):
    what = forms.CharField(required=True, label="What Needs Improvement?", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "what about this website pisses you off..."}
    ));
    how = forms.CharField(label="How Should I Improve it?", widget=forms.Textarea(
        attrs={'class':'form-control', 'placeholder':"suggestions or example of website that does it better...", "rows":'4'}
    ));
    class Meta:
        model = Suggestion
        fields = ['what', 'how']

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load staticfiles%}

{% block body_block %}

    <div class="col-md-10 col-md-offset-1">
      <div class="panel panel-default">
        <div class="panel-body">
          <p>About page bullshit</p>
        </div>
      </div>
    </div>

{% endblock %}

blog/templates/blog/add_post.html
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
  </head>

  <body>
    <h1>Add a Blog page</h1>
    <div>
      <form id="post_form" method="post" action="/add_post/" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Create Page" />
      </form>
    </div>

  </body>

</html>

blog/templates/blog/add_song.html
<!DOCTYPE html>
<html>
  <head>
    <title></title>
  </head>

  <body>
    <h1>Add a Song page</h1>
    <div>
      <form id="post_form" method="post" action="/add_song/" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Create Page" />
      </form>
    </div>

  </body>

</html>

blog/templates/blog/extra_html_snippets.html
<!-- Login Dropdown

<li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" href="#">Signup / Login</a>
  <div class="dropdown-menu">
    <h1>Login</h1>
      <form id="login_form" method="post" action="/login/">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50" />
        <br />
        Password: <input type="text" name="password" value="" size="50" />
        <br />
        <input type="submit" value="submit" />
      </form>
    <p>
      Not a member?
      <a href="{% url 'registration_register' %}">Register</a>
    </p>
    <div class="container-fluid">
      <a class="small" href="#">Forgot password?</a>
   </div>
 </div>
</li>
-->

<div class="form-group">
  <label for="playlistName">Playlist</label>
  <p id="nameError" style="color:red;display:none;">Playlist name is required</p>
  <input type="text" class="form-control" id="playlistName" placeholder="playlist name..." required="True">
</div>
<div class="form-group">
  <label for="playlistDescription">Description</label>
  <p id="descriptionError" style="color:red;display:none;">Playlist description is required</p>
  <textarea class="form-control" id="playlistDescription" placeholder="my favorite [insert genre] songs..." row="4" required="True"></textarea>
</div>
<div class="form-group">
  <label for="playlistImage">Playlist Image</label>
  <input type="file" id="playlistImage">
</div>
<div class="form-group">Playlist will be&nbsp;
  <label class="radio-inline">
    <input type="radio" name="inlineRadioOptions" id="inlineRadio1" value="False" checked="checked">Public
  </label>
  <label class="radio-inline">
    <input type="radio" name="inlineRadioOptions" id="is_private" value="True">Private
  </label>
</div>

<li><a class="nav-link" href="{% url 'blog:about' %}">About</a></li>
<li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" href="#">Blogs<span class="caret"></span></a>
 <ul class="dropdown-menu">
   {% for blog in blog_list %}
   <li><a href="/blog/{{ blog.slug }}">{{ blog.title }}</a></li>
   <li class="divider"></li>
   {% endfor %}

 </ul>
</li>

<form id="playlistForm">
  <div class="form-group">
    <label for="playlistName">Playlist</label>
    <input type="text" class="form-control" id="playlistName" placeholder="playlist name...">
  </div>
  <div class="form-group">
    <label for="playlistDescription">Description</label>
    <textarea class="form-control" id="playlistDescription" placeholder="my favorite [insert genre] songs..." row="4"></textarea>
  </div>
  <div class="form-group">Playlist will be&nbsp;
    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineRadio1" value="False" checked="checked">Public
    </label>
    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="True">Private
    </label>
  </div>
</form>


{% if post.song.video %}
{% video post.song.video as my_video %}
<img src="{{ my_video.thumbnail }}" class="img-rounded" style="width:200px;height:150px">
{% endvideo %}
{% else %}
<img src="{% static "blog/public/images/Placeholder.png" %}" class="img-rounded" style="width:150px;height:150px">
{% endif %}



var $tag = $('<script>'', {
    src: "https://www.youtube.com/iframe_api",
    }).prependTo('body');
    console.log('got here');
});


<button type="submit" id="comment-btn" class="btn btn-success" type="button" data-id="{{ post.id }}">
  <i class="fa fa-comment"></i>Post
</button>
</form>

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block title_block %}

{% endblock %}

{% block body_block %}
{% if user.is_authenticated %}
<div class="wrapper text-center">
<h2>Welcome {{user.username}} you are already logged in</h2>
<a href="/">Link to Homepage</a>
</div>
{% else %}

<div class="wrapper text-center">
<strong>Social Login</strong>
{% include 'snippets/login_buttons.html' %}
<br/>
<br />
<div class="row">
<div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
<form id="login_form" method="post" action="/login/" class="horizontal-form">
  {% csrf_token %}
  <div class="form-group">
  <input class="form-control" type="text" name="username" value="" size="50" placeholder="Username"/>
  </div>

  <div class="form-group">
  <input class="form-control" type="password" name="password" value="" size="50" placeholder="Password"/>
  </div>
  <input class="btn btn-default" type="submit" value="Sign In" />
</form>
</div>
</div>
</div>

{% endif %}
{% endblock %}

blog/templates/blog/music_genre.html
{% extends 'blog/blog_feed.html' %}
{% load staticfiles %}

{% block title_content_block %}
<div class="wrapper text-center" id="music-genre-header">
  {% for genre in genre_list %}
  <button class="btn btn-default genre-button" id="genre-button" data-url="{% url "blog:music_by_genre" kw=genre.name %}">
    {{ genre.get_name_display }}
  </button>
  {% endfor %}
</div>
{% endblock %}

{% block script_block %}
<script>
  $('.genre-button','#music-genre-header').click(function(e) {
    e.preventDefault();
   var $this  = $(this);
   $this
      .closest('#title-row')
      .next('#body-row')
      .find("#body")
      .load($this.attr("data-url"));
 });

</script>
{% endblock %}

blog/templates/blog/playlist_form.html
<form class='form-horizontal' method="post" action="{% url 'blog:create_playlist' %}">
  {% csrf_token %}
  {{form.as_p}}
<button type="submit" class="btn btn-success" id="#hiddenSubmitButton">Create Playlist</button>
</form>

blog/templates/blog/playlist_list.html
<div class="wrapper text-center">
<div class="btn-group-vertical" id="playlistButtonGroup">
  <p id="addToPlaylistError" style="color:red;display:none">You Must Select A Playlist</p>
{% for playlist in playlists %}
    <a class="btn btn-default" data-playlist-id="{{playlist.id}}">{{playlist.name}}</a>
{% endfor %}
</div>
</div>

<script>
  $('#playlistButtonGroup', '#playlistModal').click(function(e) {
    e.preventDefault();
    $(e.target)
      .addClass('active')
      .siblings()
      .removeClass("active");
  });

</script>

blog/templates/blog/profile_page.html
{% extends 'blog/base.html' %}
{% load staticfiles %}


{% block title_block %}
<div class="panel panel-default">
  <div class=panel-body>
  <div class="media">
  <div class="media-body">
    <h2 class="media-heading">Welcome {{ user }}</h2>

  </div>
  </div>
</div>
</div>

{% endblock %}

{% block body_block %}
{% if user != profile %}
<p>Hey this isn't your profile page!</p>
<a href="{% url 'blog:profile_page' pk=user.id %}">heres a link to yours</a>
{% else %}
{% if profile.likes.all %}
  <div class="btn-group" id="profileBtnGroup">
    <button class="btn btn-default mylikes-btn">
      My Likes
    </button>
    <button class="btn btn-default myplaylist-btn">
      Playlists
    </button>
  </div>
  <div class="" id="myLikes">
    <h2 class="text-center">My Likes</h2>
    {% for post in profile.likes.all %}
      {% include 'snippets/post_cells.html' %}
    {% endfor %}
  </div>
{% else %}
<h5>here is where the tracks you've liked will reside. I know its pretty bland right now so please bear with me...</h5>
{% endif %}
{% if profile.playlist_set.all %}
    <h2 id="myPlaylists" class="text-center">My Playlists</h2>
    {% for playlist in profile.playlist_set.all %}
    <div class="myPlaylists">
      {% include 'snippets/post_cells.html' with post=playlist.post %}
    </div>
    {% endfor %}
{% endif %}


{% include 'snippets/pagination.html' %}
{% endif %}
{% endblock %}

{% block script_block %}
<script>

$('#profileBtnGroup').click(function(e) {
  e.preventDefault();
  if (!$(e.target).hasClass('active')) {
    $(e.target)
    .addClass('active')
    .trigger('updateProfileBody')
    .siblings()
    .removeClass("active");
  }
});

$('.mylikes-btn').on('updateProfileBody', function(e){
  console.log('triggered');
  $('#myPlaylists').hide();
  $('.myPlaylists').hide();
  $("#myLikes").show();
});

$('.myplaylist-btn').on('updateProfileBody', function(e){
  $('#myPlaylists').show();
  $('.myPlaylists').show();
  $("#myLikes").hide();
});

</script>
{% endblock %}

blog/templates/blog/submit_music.html
{% extends 'blog/base.html' %}

{% block title_block %}
<div class="row">
  <div class="col-sm-12">
    <h1 class="page-header text-center">Recommend A Song</h1>
    <div class="container">
    </div>
  </div>
</div>
{% endblock %}

{% block body_block %}

<form id="music_form" role="form" action="{% url "blog:submit_music" %}" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
      {{ field.label_tag }} {{ field }}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Submit</button>
</form>
{% endblock %}

{% block script_block %}
<script>
$("#music_form").on('submit', function() {
  alert("thanks for the recommendation!")
});
</script>
{% endblock %}